#!/bin/sh
#################################################
# Copyright (C) 2017 Per Ivar Gjerløw
# All rights reserved.
#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.
##################################################
# Execute the git hook
java -jar .git/hooks/util/githook.jar .git/COMMIT_EDITMSG